---
  output: html_document
---

# Tālas noskaņas zilā vakarā

## * * * 

| ...Daudz simtu jūdžu tāļumā,
| Aiz tīreļiem, purviem un siliem,
| Guļ mana dzimtene diendusā
| Tā aizsegta debešiem ziliem,
| Zil-saulainiem debešu palagiem
| Pret dvesmām un strāvām, un negaisiem...




## * * *

| Bij dziļa ziema,
| Kad projām gāju
| Uz tāļu zemi,
| Uz svešu māju.

| "Nu miers virs zemes!"
| Man likās skanam,
| "Nu labs prāts cilvēkiem!"
| Pulksteņus zvanām;

| Un vējus es dzirdēju
| Ņirdzīgi smejam,
| Man paraustām svārkus
| Un garām skrejam.

| Sniegs, putens griezās,
| Man acīs sita,
| Lēni uz ziemsvētku
| Eglītēm krita.

| Ak, miers virs zemes!
| Un gara dusa,
| Un ziema, ziema ---
| Sirds sāpēs kusa.

| Man sirdī ziedons,
| Kaut eju tālēs,
| Jūs ziemas sniegi
| Tin vālu vālēs;

| Es ziedoni līdzi
| Sev piemiņai ņemu,
| Jūs viņu nievājāt,
| Skaitījāt zemu.
| Es viņu balvai
| Jums atkal nestu,
| Kad garo miegu
| Iz acīm jūs mestu...

| Vai zeme dus vēl 
| To garo miegu?
| Vai ziema klāj vēl
| To dziļo sniegu?

| Vai mieru virs zemes 
| Aizvien vēl zvana?
| Aizvien, aizvien vēl
| Jums miega nau gana?

| Es vērīgi klausos
| Šos garos gadus, 
| Vai neskan balsis,
| Kas ziedonim radus?

| Skats ilgās tiecas
| Uz dzimtenes pusi,
| Visa mana dvēsele
| Iztvīkusi.


## Aiz apmiglota loga

| Pār tevi dienas allažība 
| Kā upe lēni aizrit pāri: - 
| Zied krastā puķes, lido spāri. 
| Tu lēni peldi līdz bez vaļas...


### Agri no rīta

| Agri no rīta
| Guļ manā priekšā 
| Pilsēta, grimusi 
| Dubļos un tvaikos.

| Riebjas man nokāpt 
| Pilsētā lejā: 
| Gremdēties pilsētas 
| Dubļos un tvaikos.

| Sestajā stāvā
| Brīvs sevi jūtos,
| Bez gaļa debesis 
| Dvēselei vaļā.

| Dvēsele debesīs 
| Nepiekūst lidot,
| Līdz agrā rītā
| Miesas to atsauc.

| Miesas to atsauc: 
| Pilsētā jākāpj 
| Gremdēties pilsētas
| Dubļos un tvaikos.

| Miesas grib azaida,
| Miesas grib svārku,
| Līdzi grimst dvēsele
| Dubļos un tvaikos.


### Cilvēks un sāpes

| Cilvēka dvēsele, nabaga dvēsele, 
| Kur tev būt līdzi bezgala dabai? 
| Sāpēs un cīnīs, un grauzošās šaubās 
| Tu esi saplēsta, nabaga dvēsele.

| Daba tik pilnīga, daba tik vienalga,
| Kas viņai daļas - cilvēks un sāpes?!
| Bezgala skaista, bezgala auksta, 
| Kādu mums tēlo viņsaules dzīvi.


### Graudi akmeņstarpā

| Iedomu jaukie ideāli,
| Vecākie principi, tikla, mīla - 
| Dienas allažības priekšā
| Šķīst kā graudi akmeņstarpā.


### Dziļākās domas

| Dziļākās domas 
| Smadzenes izvaid 
| Bezveida murgos, 
| Kvēlošās jausmās;

| Domas tik plašas, 
| Tirdošas; smagas,
| Itin kā liktens
| Dzelžainā vara.

| Nekāda prieka
| Domāt šīs domas, 
| Bēgtu - kur bēgsi?
| Tver, glauž un samin.


### Pats

| Priekš citiem darbodamies, attīsti 
| Pats savus spēkus negurstošā karā -
| Un mūžīgs darba lauks būs tavā varā
| Un mūžam jaunots spēks un ieroči.

| Bet sargies būt kā nabadzīgie garā,
| Kas, sevi projām sviežot, laimīgi -
| Uz tevi spļaus un samīs tevi barā.

| Pats cīnies, palīdz, domā, spried un sver,
| Pats esi kungs, pats laimei durvis ver.


### Cieta sirds

| Tev sirds ir pilna rūgtām asarām,
| Kā rudens lietus piemirkusi pļava;
| Tās krājas tur kopš bērnu rotaļām
| Un rit, un rit, un gala viņām nava:

| Kas raudot sirdi atraisa no tām, 
| Tam labi, - viņam lāga vīra slava: 
| "Viņš atklāts, jūtīgs svešām žēlabām!"

| Tev neplūst asaras, bet pilns jau mērs, ---
| Lej asras barā - dzels kā ģifts un sērs!


### Pazudušais dēls

| Līst lieti, vēji pūš, un vakars vēls:
| Viņš vienās skrandās ģērbts un basām kājām.
| Jūs domājat, ka pazudušais dēls
| Nāk sagrauzts atpakaļ uz tēva mājām?

| Bet vai jūs neredzat, ka viņa tēls
| Ir lepni nesalauzts, ap viņa vājām
| Un kuslām miesām skrandains purpurkvēls?

| Nē, nenāk viņš, lai jūgā plecus liektu, -
| Viņš nāk kā tiesātājs, lai jūs iz tempļa triektu.



## Piekvēpis gaiss

| _"Filistieši pār tevi, Simson!"_
| _Dalila_


### Labdaris

| Bagāts viņš, bet mīkstu sirdi: 
| Dzird par grūtdienīšu raudām, 
| Tūdaļ kabatā bāž roku,
| Izvelk savu - nēzdodziņu.


### Galvas darbs

| Ko jūs brēcat, ka liktens jums skarbs?
| Jums jau taču tik rokām ir darbs.
| Vai tad nau grūtāk galvu lauzīt,
| Nekā trallinot akmeņus dauzīt?
 

### Saimnieciskas pamatmācības

#### I 

| Taupi katru kapeiciņu,
| Pēcāk būs tev simtiem rubļu: 
| Taupi ēdot, taupi dzerot, 
| Dzīvo mitrās pagrabtelpās, 
| Ja vēl tad nau simtiem rubļu, 
| Droši būs tev - agra nāve.

#### II

| Taupi katru kapeiciņu, 
| Taupi ēdot, taupi dzerot,
| Bet tik saprot' mani labi: 
| Taupi tik no svešas mutes, 
| Tad vis tukšā nepaliksi,
| Daudz būs naudas, vairāk - grēku.


### Godīgs pilsonis

| Godīgs darbs - ar svešām rokām,
| Mierīgs prāts - pie svešām mokām, 
| Ļaudis uzskata ar nievu,
| Miesas apmērs ne par tievu:

| Tevi, vīrs, es pazītu,
| Kaut vai ellē satiktu.


### Caura muca

| Tu visu mūžu dien kas dien 
| Bez atpūtas, aizelsdams skrien:
| Nest ūdeni ar retu sietu,
| Lai caurā mucā viņu lietu. -
| Kā muca tev lai pilna kļūst, 
| Uz kaimiņu viss ūdens plūst;

| No viņa aizņemta muca un siets.
| Tu savās mājās viņa iebūvēts.


### Ubagu dziesma

| Līku muguru 
| Apkārt klaidot,
| Dāvanu lūgties,
| Gaužot un vaidot -

| Zemāka liktens
| Vairs pasaulē nava: 
| Lūgties tā paša,
| Kas tevi kava!

| Kas tev atņēma
| Tavu tiesu,
| Kas tev nospieda
| Garu un miesu!

| Lūgties, lai dzīvību 
| Brīdi vēl vilktu, 
| Nabaga gaita
| Par sprīdi vēl ilgtu!

| Pirmdzimtas tiesības 
| Atļaut sev laupīt,
| Lēcas virumu
| Saudzēt un taupīt:

| Mirēji ļaudis,
| Mūžīgie nelgas,
| Nu jums no asarām 
| Acis ir velgas.

| Raudat sev, raudat, ---
| Kas gļēvos ies žēlot? ---
| Cīnīties, krist,
| Ļaut sirdij kvēlot!


### Bijušais draugs

| Viņš brauca jūrā: jaunus ceļus rast! 
| Vējš asi pūta, dzina to uz sērkli,
| Un gurdi teic viņš: "Krastā vīšu pērkli;
| Ak, laime tuvu, vajga to tik prast!"
 

### Pesimists

| Man mīļāks godīgs pesimists,
| Kas dzīves tukšumu nes, zobus griezdams,
| Ne vieglis filistris, saukts optimists,
| Kurš šķiet, ka, dzīves nastas projām sviezdams,
| Viņš visus mezglus ir jau atšķetījis 
| Tik gudris palikdams, cik agrāk bijis.


### Filistris

| Brīnums, cik drīzi, 
| Brīnums, cik ātri ---
| Vien-divos gados 
| Filistris tiki:

| Nedz brīvi smiekli, 
| Nedz skaļa runa, 
| Vispārīgs spriedums, 
| Atgremu domas,

| Nopietnas ūsas, 
| Prātīgas lūpas, 
| Deguns miermīlīgs, 
| Pamatīgs vēders!

| Cienība svārku 
| Sīkākā kroķītē,
| Līdz kurpju galiņiem:
| Krietn-krietnis tautiets!

| Jaunais tavs princips: 
| "Visur pa godam, 
| Lēnām, ar apdomu 
| Veikala lietās!

| Nevar ar pieri
| Triekties pret mūriem ...
| Dieva liktas valdības 
| Pamatus šķobīt."

| Aiz viņiem kalniem 
| Pārdrošais neprāts, 
| Degošās asinis 
| Dzesētas --- alū ... 
| - - - - - - - - - - - - - - 
| - - - - - - - - - - - - - -

| Brīnums, cik drīzi 
| Ikdienas dzīve
| Pāri tev gājusi 
| Smagiem soļiem!


### Tēvijas mīlētāji

| Kas mīlē tēviju, tiem ir savs kakts, 
| Kur lietū patverties un nolikt galvu;
| Tiem miera prāts un maizes rieks par balvu, 
| Tie maz ko bēdā, lai visapkārt nakts.

| Bet vai! par tiem, kas straujāk slēdz to sirdī, ---
| Tie liktens āmuram ir smēdes lakts,
| Tos tēvuzemes sāpes kaļot tirdī ---

| Bez poēzijas piekaļ tos pie cietas 
| Pie tēvzem-sienas, rokas top tiem sietas


### Prātīga rīcība

| Es dzirdu, dzirdu: --- tagad jau gan
| Jūs saprotot, ko dziesma skan,
| Ko dziesma skan, ko zvani zvan, ---
| Bet cik tas palīdz jums, cik man?

| Jau pirmais pārsteigums pārskrējis, 
| Dažs labs pie jaunā puspieradis;

| Viens otris vārdiņš pie sirds arī ies: 
| "Nudien, tas brangi. tur teikts, paties!"

| Un paslepšus dažs vēl piebildīs:
| "Es cerēju pats to, kaut ne tik drīz ---"

| Jā, cits pat atklāti teiks: "Nekas,
| Bet jāsargās, ak, kā jāsargās!

| Tā lieta par strauji maķenīt ---
| Vai tā nu ir jāuztraucas tūlīt?

| Ar galvu jau nevar caur sienu skriet, 
| Ir taču jāpaciešas mazliet.

| Un kas nu tūdaļ pie sirds tā ņems, 
| Gan liktens labākas dienas tiem lems;

| Ar joni jau nepanāksat neko,
| Vajaga mierā būt ar vismazāko;

| No dieva puses, ar varu tik ne,
| Tas pats sev kaitē, kas paģērē;

| Un, kurš vēl top rupjš, kad tiesu tam liedz,
| To atstās ikkurš, lai tad sev kliedz!

| Jo vienīgais ceļš tik ir gaidīt un lūgt,
| Kurš laipni prot palūgt, kas tādam var trūkt?

| Bet, kurš ir tiepša, lai pirkstos sev kož,
| Kad kaimiņa rovītē cepeti ož.-

| Nu, cerēt, --- to var, tas kaitē maz, 
| Ja cerības tikai nau aplamas.

| I dzejā jau dažu saka, kas lieks.
| Par jaunības dūšu mums slepeni prieks.

| Bet dzīvē pārmērs un lepnība
| Ir tie, kas karjeru izposta, ---

| Tad labāk ir desmitreiz muguru liekt,
| Ne vienreiz par netaisnību kliegt.

| Ar laipnību, lēni viss jāiesāk ..." 
| --- Jā, jā, līdz pat pļaukas panest māk;

| Lai spļauj tev acīs, tu noslauki vien,
| Jo pilsonim pretī sist nepiedien!

| --- Es sen jau šo mācību dzirdēju, 
| To sauc par "prātīgu rīcību".
 

### Miera ļaudis

| Viņš savu dvēseli jums pretim nesa 
| Kā rīta sauli sārtos mākoņos,
| Un vēsi vēji jums uz pieri dvesa.

| Jūs segu dziļāk pārvilkāt pār ausīm 
| Un notrīcējāt aukstos drebuļos:
| "Vai saldu mieru mēs sev laupīt ļausim?

| Mums viņa dvēsle sirdis nekustina,
| Tā sauc mūs nezināmos tālumos -
| Vai tā jel maz ir atļauts, dievs to zina?

| Vai tiešām mēs lai pakaļ ejam tādam, 
| Kas daili noved dzīves bezgalos -
| Mēs viņai glītu miera ceļu rādām.

| Mums sirdis rāmas, dvēsles mieru bauda, 
| Lai saldos sapņos mīļi aijātos,
| Kur ziedos daiļas rociņas mūs glauda.

| Kas saldo mieru trauc ar špetnām rokām, 
| Grib daili vest, bet jaucas traipekļos,
| To īgni atstumjam uz mūža mokām ..."

| Vēl daudz tie triec, to pašu vis par jaunu,
| Tērpj gļēvās domas greznos vizuļos,
| Aiz skaļiem vārdiem slēpt grib savu kaunu.

| --- Bet savu dvēseli viņš tālāk nesa
| Kā rīta sauli sārtos mākoņos,
| Un vēsi vēji viņas priekšā dvesa...
 

### Pirmie vēstnieki

| Pirms vēl sniegs bij sācis kust,
| Nāca sīki gāju putni, 
| Pirms vēl sācās pavasara
| Saules siltā, zaļā vara.

| Putnu skaļām balsīm klust,
| Klust un aizsmakt vajadzēja:
| Zemei viņi neiedvesa 
| Ziedoni, ko krūtīs nesa;

| Viņi lika iepriekš just, 
| Cik būs krāšņa nākamība, -
| Gavilēja, drīzi rima,
| Tad tikai sākās ziedoņa dima.



## Trejkrāsainā saulītē 

| _Saul' un mēness velti iet_
| _Tavām acīm garām..._


### Senatne

| Tur burvīgā gaismā viss zaigo un laistās, 
| Ik skaņa tur dziesmās un saskaņās saistās;

| Pār pļavām, pār mežiem tur meitenes līgo, 
| No kalna uz kalnu jāņugunis spīgo;

| Visapkārt kā noslēpums drūmi guļ sils;
| Tur glāžu kalns mirgo, tur ūdens pils;

| Iz niedoļa nāras saldsērīgi smejas,
| Un mēnesnīcā tur laumas vij dejas;

| Bez saulītes vakarā bāri tur dzied,
| Tie bargu kungu gaitās iet...

| Bet melnā čūska maļ jūrā miltus,
| Tos jāēd būs tiem, kam vara un viltus;

| Tur karā jāj bāliņš --- aust asiņains rīts,
| Pret ienaidniekiem ass zobens trīts,

| Tad augšā kāps pilskalns iz senseniem laikiem,
| Iz simtgadu miega caur dūmiem un tvaikiem.

| Dies saulīte atkal trīskrāsaina:
| Drīz zila, drīz zaļa, drīz sarkana.



### Karaļmeita

| Tanī niknā dienā 
| Asins šļācot šķīda:
| Grima zemē pils un karaļmeita...

| Daiļā karaļmeita
| Sēd tur dziļā pilī,
| Sēd un vērpj jau seši simti gadu.

| Pilī dzintarsienas,
| Zaļa vara grīda,
| Gliemežgriesti, sijas tēraudzilas;

| Daiļai karaļmeitai 
| Dunošs pērkoņratiņš,
| Dimantspole, zibens pavedieni;

| Sēd tā zelta krēslā,
| Acis drūmi kvēlo, 
| Sēd un vērpj; tai melnais suns pie kājām.

| Melnais suns pa laikam
| Norūc, paceļ galvu,
| Tālu augšā juzdams asins smaku...

| Viņā niknā dienā,
| Asins šaltēm šļācot,
| Celsies augšā pils un karaļmeita:

| Karaļmeita audīs
| Jaunus gaismas audus ---
| Zibens meti, audi varavīksnas.

| Jaunās gaismas audi,
| Līdzi saules segai,
| Silti apņems visus sāpju bērnus.
 

### Lauka lilijas

| Jūs nezūdaties savas dzīvības,
| Ko ēdīsat, ko dzersat rītu,
| Nedz arī savas miesas apsegas,
| Iekš kā to mīlīgi un silti tītu.

| Jūs esat it kā putni gaisos brīvi:
| Nedz viņi sēj, nedz viņi pļauj,
| Nedz klētīs krāj, nedz kaudzēs krauj, -
| Un vai tiem maizes trūkst, ko elpēt dzīvi?

| Jūs baro jūsu tēvs pārpilnībā
| Un zemie zemes pīšļi tīrumā,
| Ko jūsu kājas min.

| Jūs esat skaistās lauka lilijas. -
| Kā viņas zied un sārtojas!
| Tas krāšņais, priecinošais skats! - -
| Nedz viņas strādā, nedz ar vērpj.
| Un es jums saku: lielais Zālamans pats,
| Kaut sevi visgreznākās drēbēs tērpj,
| Ar visām pasauls spožām lepnībām
| Nau līdzīgs vienai vienīgai no tām.

| Tik --- lepnā zāle, --- to tie pīšļi zin, ---
| Šo dienu stāv un rīt kļūs aprīta
| No zemes pīšļiem un no tīruma,
| Ko tā, iz viņa spēku sūkdama,
| Ar kājām min.


### Zemnieks

| Smagi zemnieka lēnie soļi nodun,
| Kad viņš darbojas laukā sūros sviedros,
| Kad viņš atpūtā svētku dienās staigā.
| Steigties nākotnei pretim nau viņš radis,
| Skats tam atpakaļ klīst aizvien uz druvām.
| Cieti ieaudzis stāv viņš savā zemē,
| Lidot nejauzdams augstos, zilos gaisos,
| Spēkus sūkdams iz krūtīm zemes mātei.
| Tīrais milzeņa bērns, tik liels un lempīgs,
| Bet, kad celsies, viņš rokām lāčus plēsīs


### * * *

| Tas nau tik grūti pravietot
| Par laimi, rītu un sauli:
| Jā, tiešām, liktenim vajadzēs tos dot,
| Bet sen jau tad dusēs šie kauli, -

| Tie dusēs un trūdēs, un odīs pat,
| Tad jauno sauli jūs redzēsat.


### Fabrikas meitenes dziesma

| Ak, lakstīgala, nedziedi
| Pie mana loga sērīgi, 
| Man rītu agri jāceļas,
| Sirds kūst man vienās žēlabās, 
| Sirds tavām dziesmām līdzi kūst, 
| Kā viņas līst un rimst, un plūst.

| Man rītu agri jāceļas,
| Man saules nau tais istabās, 
| Tur putekļi, tur lampas kūp, 
| Tur lēni mana dzīve drūp, 
| Tur lēni, tā kā pulkstens sit, 
| Man velkas stundas sešpadsmit.

| Tu šūposies vēl saskaņās
| Līdz rītam, kad man jāceļas,
| Tev birzē ritēs rasas zelts,
| Man vecais slogs būs plecos velts ---
| Ak, lakstīgala, nedziedi
| Pie mana loga sērīgi!


### Viņš to zināja

| Viņš to zināja
| Visu to laiku,
| Kopš viņu sērga
| Iesāka kratīt;

| Viņš to zināja,
| Sen jau zināja:
| Viņam bij jāmirst
| Šinī sērgā...


| Viņš visu redzēja,
| Viņš visu saprata:
| Kas bija bijis, 
| Kam bija jānāk...

| - - - - - - - - - -
| - - - - - - - - - -

| Ap viņa gultu
| Stāvēja bērniņi
| Mirkušām piedurknēm, 
| Šņukstošiem deguniem;

| Sausām acīm,
| Drebošām rokām
| Sieva tam pasniedza
| Pēdējo malku...

| Visu viņš redzēja 
| Gaiši kā dienā, 
| Kas viņa mīļajiem 
| Dzīvē bij gaidāms;

| Visa viņa dzīve
| Līdz sirmiem matiem,
| Pūlēs un sviedros,
| Bijusi velta ---

| Nebija spējis
| Sievai un bērniem
| Sagādāt vairāk 
| Kā nabagu māju.

- - - - - - - - - - -
- - - - - - - - - - -

| Viņš visu redzēja
| Un tad mira,
| Zobus iekodis
| Pagalvja salmos ---

| Skaidra apziņa
| Palika viņam
| Līdz pat pēdējam
| Acumirklim.


### Jauna gadusimteņa nakts domas

### Fragments

#### I

| Man apkārt trimdas aukstais tuksnesis: 
| Še droši sēdēt man, še laika daudz;
| Iz lielās tāles jauno gadsimteni
| Var agrāk, skaidrāk redzēt atnākam, ---
| Un mīļā dzimtene guļ manā priekšā
| Kā plaši izplatīta balta sega,
| Ar zilu jūras lentu apšūta;
| Zem baltās segas svaigi kapi - - -
| No svaigiem kapiem svaigas asins kūp,
| Nupat tik izlietas, jo tiešām tās
| Bij pārāk karstas vecam gadsimtenim.
| Jauns gadsimtens varbūt tās lietā liks.

#### II

| Kā zaglis naktī, tā viņš atnācis,
| Tik lēniem, nedzirdamiem glūņas soļiem,
| Bet pēkšņi durvis brakš, --- un mūža slieksnis,
| Tik zobens ass, tik zibens īss --- ir pārkāpts,
| Un acu priekšā sarkans izplešas
| Kā ziemeļblāzma - jaunais gadsimtenis,
| Viņš virsū veļas milzīgs, plašs un smags. 
| Bet mūža durvis rībot cieti krīt,
| Un laiks gar durvīm šņācot aizšaujas. ---
| No jaunā gadsimteņa aukstums dveš,
| Ap kājām kūpot viļņo garaiņi,
| Aiz viņa draudošs, noslēpumains tumsums,
| Tik zvērās acis dzirkst iz segtā vaiga.

#### III

| Jūs jaunā kunga svina roku jūtat
| Uz sava kakla, pirms vēl iespējāt 
| To saņemt pienācīgām gavilēm,
| Ka atpestījis jūs no vecā sloga.
| Jūs mirdzin skaidrās glāzes pacēlāt -
| Iekš viņām putoja ekscelsiors -
| Viņš jūsu glāzes drupās sašķaidīja,
| Un saldais, nevainīgais dzēriens lipa
| Pie jūsu zolēm. - Arī viņam kauss
| Bij rokā - glums un sarkans receklis, -
| Bet otrā rokā viņam bija vējš, -
| Viņš to jums acīs sēja smiedamies,
| Ka būšot vētru pļaut - un galvas pļaut -
| Jūs miera ļaudis - - - - - - - - - -
| - - - - - - - - - - - - - - - - - - - -

#### IV

| Ko viņš mūs grābj tik pēkšņi un tik bargi?
| Kāds šis mums pavēlnieks? Kas šis tāds ir?
| Kas pazīst viņu? --- Mūžu klaidonis.
| No kurienes viņš nāk? --- No tukšuma.
| Kurp iet? --- Uz tukšumu --- un neziņā
| Viņš atkal pazudīs, kā atnācis.
| Visvarenākā kunga "Laika" priekšā
| Viņš tikai mirklis, skaitlis, zemīgs kalps...
| Mums jāgrib, un mēs viņu locīsim,
| Lai kalpo mums, kas ir mums pavēlnieks.
| Sviest viņu nost! Vēl viņa roka spiež -
| Cik ilgi vēl? - - - - - - - - - - - - - - - - - - -

#### V

| Dēls gluži vecajā; nau izšķirams,
| Kad vecais gājis, jaunais uzstājies.
| Dažs teic, jau pērn, un tādā kārtā viņš
| Jau slepus gadu būtu valdījis,
| Un tēvs ar saviem diviem 9-iem
| Tā aizgājis kā divi deviņi.
| Dažs atkal teic: viņš ļāvis tēvam dzīvot,
| Līdz tas jau būtu nonācis līdz 0, -
| Lai rādītu, ka vecam gadsimtenim,
| Kurš iesākās tik grezni, - iznākums
| Ir nulle, - nulle nulles galā.
| 1899.-1900.

#### VI, VII

| Un kas tad bij šis viņa tēvs? Kas māte?
| Teic: gars un mūžība! --- Tie tikai vārdi: 
| Tēvs --- vecais pilsoniskais gadsimtens,
| Un māte --- staltā Vaļība? --- par kuru
| Viņš karstām jaunasinīm cīnījās. ---
| Tam nebij lemts to iegūt, bet --- tā melš ---
| Šis neatļautais mīlestības sakars
| Bez sekām nebijis. --- Un tomēr viņš,
| Kā daždien pilsons, vēlāk precējies
| Ar savas kārtas drukno Ikdienību
| Un metis jaunu dienu untumus ---
| Un ticis pats par ļaužu apspiedēju. - -
| - - - - - - - - - - - - - - - - - - - -

#### VIII, IX

| Kad tēvs jūs beigās kūla pātagām,
| Tad dēls kuls skarpijiem. --- Viņš atnāca,
| Līdz elkoņiem, kā miesnieks, aptriepies
| Ar svaigām asinīm, ---
| Par mieru mēļodams un klusām kaudams
| Pa pulkiem nevainīgus upurus
| Par labu kultūrai un gara gaismai.
| Viņš tautas asrās slāpē, žņaugos žņaudz,
| Tām mutes aizbāzdams, lai pārāk nebrēc:
| Jo tā tik klusa māju darbība,
| Un sodāmi ir tie, kas pārāk brēc,
| Jo tas ir dumpis - - - - - - - - -

#### X

| Viņš savu gaitu sāk ar kara troksni, ---
| Tā pirmie soļi norīb tālienē
| Kā "garā Toma" rupjais bass, --- tā kāja
| Pret mīksto miesu šļākstot sper kā lode, 
| Visapkārt sprakstot zilās pupas plīst ---
| Eiropas koncerts, tā šo troksni sauc,
| Kur lielgabali dūc, kur šrapnels sprāgst,
| Kur kara vaidus dumdums pārdimdo,
| Kur zobi šņirkst un dzelžu bruņas klaudz;
| Bet visam pāri liegi fleites dzied ---
| Pus-saldi glaimīgi, pus-ņirgājoši, ---
| Par kluso, netraucēto laimību,
| Ko nesis spožais, smailais asmenis,
| To sauc par diplomātiju ---

#### XI

| Viņš grib, lai klusums valda, --- kluss un kluss! ---
| Lai nerūc lielgabali, nešauj šautnes,
| Lai zobens nedur, jeb vismaz bez trokšņa;
| Lai vaidi rimst, lai klusi sten, kam jāsten;
| Lai zobu žogā sakniebj īgnumu;
| Lai mēli piesieri - vien par visām reizēm, 
| Tā grēko vairāk, nekā spēj to sodīt: ---
| Tad visi brēķi brīnum ātri rims,
| Tad jauno gadsimteni nepels vairs, 
| Tad zudīs dusmas, vaimanas un lāsti,
| Nāks miers un pilnums, cilvēkiem labs prāts,
| Un tikai reizām, spējāk kustoties,
| Kā sīki zvārgulīši dzelži stinkšēs,
| Kas mīkstā tūbiņā būs ietīti.
| Jo žēlsirdīgs mums ir ij soģis pats;
| Ij bende pats liek savam asrām līt,
| Kur asnis lej.- - - - - - - - - - - - - - - -
| - - - - - - - - - - - - - - - - - - - - - - - -

#### XII

| Nu, kāda būs tā tava Leiputrija,
| Ko vecais gadsimtens jau dzīrās nest,
| Uz mieru, bet uz miegu dibināta?
| Jo maza tikai bij tā Leiputrija,
| Ne daudzi guva viņā mieloties,
| Drīz bija nosukāts viss putras kalns,
| Bij izdzerts vīnezers ar visām dūņām,
| Pagalam desu žogi, šķiņķu sienas,
| Un visa saimniecība izpostīta ---
| Bet pāri palika no visas laimes
| Tik pliki nomīdīti tīrumi
| Un kauli - - - - - - - - - - - - - -

#### XIII, XIV

| Mēs gaidām citu, jaunu Leiputriju,
| Ko neiztukšotu tas augšējs tūkstots.
| Kas būtu diezgan liela it priekš visiem;
| Kur būtu miers, ne miegs, bet dzīvība, 
| Un katris brīvi spētu klamzāties
| Un rokas izstaipīt - Vai dosi to? 
| Ik dienas maizes riku, sviestu virsū
| Un gaļu klāt? Un svārkus, zābakus
| Un pīpē tabaku, un sievām kleites,
| Un svētdien biļeti uz teātri?
| Pa mazam strādāt, ēst un dzert papilnam,
| Kā talkā, visiem līdzi darbs un galds?
| - - - - - - - - - - - - - - - - - - - - - -

#### XV, XVI, XVII

| Mēs neapslāpējamās mūžu ilgās
| Daudz gadusimteņus jau gaidās tvīkstam
| Pēc gaismas, laimes, vaļības un maizes,
| It sevišķi pēc maizes, - kviešu maizes,
| Par līku vērdiņu par mārciņu;
| Jo līdz ar to mums piekritīs viss cits,
| Kas daiļš un labs, un tiklis, prāts un gars -
| --- Un zini to: mēs esam paaudze,
| Kas netop veca, vārds mums leģions; 
| Tā aug un aug un tevi veic un liec:
| Tu būsi mūsu vergs --- _nos vincemus!_ ---
| --- Tad beigās izaugs pastars saules dzimums
| Uz skaidrās sniegabaltās svētku zemes, ---
| Tas baudīs laimību bez visa gala,
| Ko mūžusāpēs mēs tam ieguvām ---
| Ar trimdām, cietumiem un asins mokām
| Mēs, negaidošie aplam cerētāji,
| Kas ķērās bārdā pašam Laika tēvam 
| - - - - - - - - - - - - - - - - - - - - - - -


### Vārdi

| Visas dzejiskās sēras un gaviles,
| Jūtu visas plūsmas iz dvēseles -
| Spēj tikai dienas mūžību kavēt,
| Nau jau tie vārdi, ar kuriem var zavēt: 
| Tālumus pārcilāt,
| Kaut ir par sprīdi pie mērķa klāt.



## Zem vientulības tumšzaļajiem spārniem

| ... Pāri upei mēness meta 
| Tiltu zelta stariem:
| Pārnākt sapņu gariem
| Miglai līdz iz tumšiem mežiem.


### Rasa klāja zemes vaigu

| Tālos mežos saule slīka:
| Rasa klāja zemes vaigu,
| Sārta blāzma vaigā tvīka;

| Visu nakti rasa rita, 
| Balti klāja zemes vaigu, 
| Zaļā sagšā mēmi krita;

| Saule pārnāk, atrod rītu:
| Rasas klātu zemes vaigu,
| Baltā asru autā tītu.


### Balta laime

| Bez gala upe sniecas
| Uz ziliem kalnājiem.
| Tur debess pret zemi liecas 
| Aiz mūžu tālumiem;

| Kur debess ar zemi tiekas, 
| Kur tālums neplūst vairs, 
| Tur balta laime man liekas,
| Tur tu, tur nogrimst dairs.


### Vakara miers

| Pie debess malas, 
| Mākoņu piespiesta,
| Guļ vakarblāzma, 
| Dziestot vēl zudina.

| Tāļš uguntiņš kuras, 
| Nelīdzi mirgojot,
| Griež pļavā grieze ---
| Miera sirds negrib tev dot?

| Lēn-lēni dziļāk
| Tumsa uz zemi līkst, 
| Velgs vēsums staigā, 
| Galva tev rokās tvīkst.


### Mūžība

| Zil-augstu kalnāju 
| Sniegotā gultā
| Guldīju galvu, 
| Lūkoju tālē...

| Pār kalnu kalniem,
| Aiz zvaigžņu zvaigznēm, 
| Līdz manas acis 
| Nesniedza redzēt:

| Līdz manas acis 
| Nesniedza redzēt, 
| Līdz visi prāti 
| Mulstin mulsa.

 
### Miglas lokā

| Ko, senais sapnis,
| Tu dvēsli moci,
| Tās tālās dienas
| Pa miglu loci?

| Ar klaidu tēliem 
| Celies un plūsti,
| Kā plašos tīklos 
| Dvēseli gūsti?

| Caur tīkla acīm
| Mirdz birzes cauri -
| Dvēselei gūstā
| Tik šauri, šauri.

| Uz tālām dienām
| Ceļš lokā vijas, 
| Sapņainie tēli
| Plūst un mijas.


### Sirds tik grūta

| Smagi sēri
| Lauku mātes
| Elpa pūta;

| Pāri pļavām
| Rudens tvaika
| Vēsmu sūta.

| Vēsmas drēbe
| Pelēkzīda,
| Miglas šūta;

| Pērļu smaga
| Vīle velkas,
| Liecas rūta -

| Nobirst rūta, 
| Nobirst astra - -
| Sirds tik grūta.


### Jūras vaidi

| Iz tālām, senām dienām
| Man dzirdas, ka jūra krāc,
| Pret smagām smilšu sienām
| No dusmām putas šļāc.

| Jo ilgāk klausos, klausos,
| Jo drūmāk skan šī balss,
| Es klausos mūžīgos gausos 
| Vaidos, kad būs viņiem gals?


### Priekš negaisa

| Pus-pelēks un pus-tumši zils
| Spīd ūdens pretī debess jumam,
| Kurš mēms un ciets kā tēraudpils,
| Un vienmuļīgs līdz apnikumam.

| Kā spoguls jūra... malās vien
| Viss tālā ūdens lauka garums,
| Kur pāri vēju drebuls skrien,
| Ir grumbās izvagots kā arums.

| Virs ūdens kaiva baigi slīd,
| Pus-bailes kliedzienā, pus-raudas; -
| Drīz kaiva krīt, drīz balti spīd,
| Kā dvēsele bez miers šaudās.


### Vēls vakars

| Viz bāli zaļgans zaigums debess tālē,
| No saules rieta zelta migla plūst,
| Vēl rasa reti mirgo velgā zālē,
| Un siltais gaiss kā maigā veldzē kūst...

| Bet krāsas gurdamas jau nīkst un bālē,
| Nakts vēji dzestri, slepeni sāk pūst ---
| Un zemi tumsa gulstas smagā vālē...

| Bez veida, mēra, dzīves... Žņaudzas krūts,
| Salst šalkas, tukšums veras, --- diezgan būts.

 
### Bula laiks

#### I

| Uz debess dziļi gulies mākonis
| Un smagā tumsā sauli žņaugdams sedzis; 
| Aiz segas uguns, kurš tik verdošs dedzis, 
| Kā matu zelts līst šķiesnām iziris.

| Un mākons lēni kāpj, - sirds raujas baigi -
| Pus-debess juma slogs jau apņēmis;
| Kā nasta garu spiež, un mācas vaigi -

| Un žēlums nevairāms uz krūtīm slīkst, 
| Pēc tāliem saules krastiem ilgas tvīksi.

#### II

| Bet mākons kāpj un kāpj... un tumsa sok,
| Bez laika slāpēdama gaismas dzīvi:
| Lauks drūmi klust, bet debess dun jau spīvi,
| Pie zemes bezdelīgas bikli plok.

| Tad pēkšņi dārd, un alpām auka brāžas, 
| Rauj koku saknes, ūdens dzelmes lok
| Un, kaucot šļākoņam, pret zemi gāžas:

| Ar smagu kāju dzīvi mīt un lauzt,
| Ar špetnu roku zemes vaigu šaust.

#### III

| Un beigās nomākts viss --- tik plaša nakts:
| Tāļš zibens zibsnī, tukšs un stindzis mēmums, 
| Kā raudot lietus līņā: varas lēmums
| Ir piepildīts, un nāve stāv kā vakts.

| Gars pagurst, rokas slābst: ne celt, ne locīt! 
| Tik retu siržu plēnēs kvēls vēl rakts,
| Ko domas dzelt, ko dvēsli sapņiem mocīt!

| Gaiss drēgnis, auksts --- caur kauliem šalkas dzen;
| Kā baigas balsis purvos klīstot sten. ---


## Nakts ēnas

| ...Aukstā dvēsle, lepnā dvēsle
| Ne paļāvības, ne pieticības 
| Bez gala vientuļa, bez gala brīva,
| Ne mērķa, ne zvaigznes, ne vēlējuma...


### Vecās ligas

| Vecais dzīves riebums atkal 
| Paceļas iz savas migas, 
| Viņam līdzi vecās ligas 
| Visas dzīvas, tās tik snauda.

| Lēni viena pakaļ otrai 
| Glūnot tās iz tumsas rāpjas, 
| Atpakaļ no gaismas kāpjas, 
| Bet tad tālāk lien pa mazam;

| Jo pa mazam, salīkušas
| Lien gar zemi biklā gaitā, 
| Vēl un vēl, bez gala skaitā; 
| Auksti mirdz pa reizēm gļotas.

| Glumās būtnes nevairāmas, 
| Netveramas tavām rokām; 
| Viņas pilda dziļām mokām 
| Visu miesu, visi, garu.

| Riedamies tu viņas nēsā 
| Neredzami savās krūtīs;
| Nau neviena, kas gan sūtīs 
| Pestīšanu tev no viņām?

| Velti raugies baiļu acīm ---
| Tev tik smiekli līdzēt spētu,
| Asu dzelžu šķēpu sētu
| Tie tev apkārt sargam celtu.

| Tavā mutē neskan smiekli,
| Tavas lūpas neprot smaidīt ---
| Veltin tevim cerēt, gaidīt:
| Lejā dziļā nakts jau klājas.
 

### Pamazītēm

| Pamazītēm un pa vienai 
| Dzīves dzīslas jūs man rāvāt, 
| Jūtas, domas slepu kāvāt,
| Ik pa stundai, ik pa dienai ---
| Nu jūs stāvat, brīnāties:
"Bāls kā nāve, mīļais dievs!?"


### Īsie pantiņi

| "Ko esat, pantiņi, tik īsas elpas,
| Kā pušu plēstas, biklas nopūtas?"
| --- Ak, jāsteidz izteikt, --- gaust nau laiks, nau telpas,
| Drīz sarkanšvītras pantos iegriežas.


### Telpas nau

- - - - - - - - - - -
| Telpas nau izstaipīt 
| Tirpinošās dzīslas; 
| Smadzenēs slāpētas 
| Degošas domas:

| Smadzenes sagruzd. 
| Locekļi sarūst,
| Kā veca mašīna 
| Klabošiem dzelžiem, 
| Kaucoša griežama, 
| Sviežama projām 
| Lūžnāja kaudzē...
- - - - - - - - - - - - -


### Ziedu sapņi

_Lai es dzīvību nīstu._
_Tuksnešos bēgtu,_
_Tādēļ ka ziedu sapņi ne visi_
_Ienāca augļos._
_Gēte. Prometejs._

| Viss vīlis, viss kritis un zemē rakts,
| Apkārt tev noslēpums, šausmas un nakts ---
- - - - - - - - - - - - - - - - - - - - - - - - - - - -

| Sakost tik zobus un dzīvi nest,
| Kamēr vēl krūtīs spēj dvašu dvest, ---

| Sakost tik zobus un ciest, un ciest,
| Lai arī pēdējā cerība dziest,

| Lai visi locekļi lūst un ļimst:
| Tumsas dziļumos gaisma dzimst!


### Vēl ziema

| Ja galvā doma tev dzimst 
| Zini: tā atpakaļ grimst, 
| Neredzējusi saules un rīta;

| Ja krūtīs jūta tev dīgst
| Zini: kā puķe tā nīkst,
| Zemē dzelžainu pakavu mīta;

| Tu glābdams roku sniedz ---
| Zini: pats staignī stiedz,
| Roka tevim valgos būs pīta ---

| Nakts bez rīta tev draud...
| Tomēr --- tu iesi, kur raud, 
| Iesi, kur ziedons zēla un vīta,
| Dziļā dzīve vēl  ziemā dus tīta.


### Kalnā kāpējs

... Tad kļūsi vientulīgāks gads pēc gada,
| No tevis atšķelsies pēc drauga draugs,
| Rets ceļotājs, kas būs tev dvēslē rada,
| Un reta puķe, kas tev klintīs augs.

| Tad zudīs arī tie, - un kalnu tālos
| Bez gala klusums sirdi tevim žņaugs;
| Tev nebūs dusas atrast ledus gālēs:

| Visapkārt tevi ledains vairogs segs,
| Bet visas zemes ilgas krūtīs degs.


### Viens

| Tu esi viens no mūžības,
| Un viens tu paliksi līdz galam,
| Līdz tavas dzīves atliekas 
| Tiks ļautas pirmatnības salam.


### Mūsu dienas

| Iet dienas tukšas, vilkdamās,
| Drīz austra, drīz dziesna tās krāso...
| Bez spēka tās, bez jēgas tās,
| Kā asins iz brūces tās lāso...


### Visu mūžu 

#### I

| Visu mūžu gāju maldā,
| Dziļās sāpēs dvēsle tvīka, ---
| Beigās turu sevi valdā: 
"Dzīvot! dzīvot!" --- spēki slīka.


#### II

| Vīta puķes saulzarainas-
| Dzīve netop . . . ainas! ainas! 
Žņirgstot žņaugtās puķes plaka- 
| Visu klāja zemes smaka.


### Patiesa dzīve

| Nē, nau tās vairs dzejas sald-sāpīgas jausmas,
| Nau sapņu tirdošās, draudošās šausmas ---
| Tā patiesa dzīve bez apsega:
| Pelēka, netīra, pūstoša.
 

### Mūžības priekšvakarā

| Nu vajaga mirt!
| Es gļēvs savu mūžu neesmu bijis,
| Es smeldzošās sāpēs sev izcīnījis 
| Dvēseles tvirtumu bezveidā nirt.
| Nu vajaga mirt!

| Un tomēr... man riebj, mani drudzis krata
| No nāves šausmaini zemiskā skata; 
| Izplešas acis, saceļas mats pēc mata... 
| Dzīvības sakariem visiem būs irt?
| Nu vajaga mirt!

| Nu vajaga mirt?
| Un dzīve tīr-skanoša tapa un plaša...
| Darbs, tu mans nebeigtais! --- Aizraujas dvaša ---
| Atpakaļ pirmatnes atomos birt? ...
| Nu vajaga mirt!


## Zelta tvaiks

_... Mana dvēsele atkal augšup nirs,_
_Un aizbēgs šausmainie biedi,_
_Kad smaršaini manim virsū birs_
_Tavas mīlas baltie ziedi..._
_Aspazija_


### Kopš garas mūžības

| Bet nekustošais ķermenis
| Ne mīlas sajūt, ne naida 
| Viņš, atsalis un sastindzis,
| Guļ slēgtām acīm un gaida.

| Viņš gaida siltas asaras,
| Kas tam uz krūtīm lai litu, 
| Viņš gaida kopš garas mūžības,
| Lai celtos uz gaviļu rītu.

### Zaļā pavēnī

| Sāk lēni slēgties sirdī vāts,
| Kas ilgus gadus čūlojusi,
| Tik ilgus, ilgus tukšus gadus ---
| Tu mazo rociņu man klusi
| Uz vārgo sirdi uzlikusi:
| Sirds atkal silst un staro prāts,
| Un aizmirsta dziļā, dziļā vāts.
| Sirds karstā, klusi!
| Grūts ceļš tev priekšā, drīz, drīz tevi cels, ---
| Dusi vēl, dusi!


### Alkanā zeme

| Pār zemi pārlaidās pāri
| Melns mākonis valguma
| Un alkanā zeme kāri
| Pēc viņa dvašoja:

| "Ne laimes, ne saules, - bet dzēsmas!
| Kaut tumsā un dubļos viss slīkst,
| Ilgi ilgotas veldzošas vēsmas,
| Lai jaunzaļi asni dīgst!"

| Un vienmēr zeme kāri 
| Pēc zēluma dvašoja,
| Kad augsti pārlaidās pāri
| Liegs mākonīts valguma.



### Silts dvašas vilnis

Ņirb saulē jūra bez gala; 
| Mazs namiņš, apkārt mežs: 
| Uz zemi, kur ziema un sala, 
| Silts dvašas vilnis dveš.

| Es jūtu, ka tava dvaša
| Man dvēselē iespiežas,
| Man dzīvība briestoši plaša 
| No viņas atmostas;

| Tā ņirb kā jūra bez gala,
| Bez valda plūstoša,
| Uz sirdīm, kam ziema un sala,
| Vasaru staroša.


### Sabirzis ziediņš

| Maigu mīlas vārdu 
| Glāstoša veldze, 
| Kūstošu ilgu
| Kvēle un smeldze:

| Sīks, sabirzis ziediņš
| Man vairāk sver, ---
| To manas rokas 
| Taustāmi tver; ---

| Sīks, sabirzis ziediņš, ---
| Zīdautā tīts, 
| Viņš bija toreiz
| Tev matos vīts.


### Niekabīle

| Man plaši vērtā logā
| Līst sēras gaviles, ---
| Tās lakstīgala pogā
| Dziļ-dziļi iz dvēseles.

| Bet viens tik viņai teiciens, 
| Tas pats maz skaņās beigts, 
| Viens vienīgs mīlas sveiciens, 
| Tik mūžam no jauna teikts.

| Ak, tādu niekabīli
| Es arī pazīstu, ---
| Teic: "Mīli! mīli! mīli!"
| Caur visu mūžību.


### Zilganas dzirksteles

| Ko veļas drausma, ko baisma,
| Ko vaigi tev asarās mirkst?
--- Kā skaļa gaviļu gaisma
| Iz tavām acīm dzirkst;

| Met zilganu dzirksteļu mirgas
| Iz spēka pilnās sirds:
| Klīst smacin biezās birgas,
| Gaiss dzidrā skaidrībā mirdz;

| Dziļ-dziļi dvēselē zaigums
| Un mīla, un mūžīgs rīts,
| Un miera netrauktais maigums, 
| Dzeldošās ugunīs tīts.

| Ko veļas tad drausma, ko baisma, 
| Ko vaigi tev asarās mirkst, 
| Kad skaļa gaviļu gaisma
| Iz tavām acīm dzirkst?


### Velna skuķis

| Un kaut tu ņemsi citu,
| Tev nebūs miera gūt,
| Es acis tai izskrāpēšu,
| Tev tomēr manam būs būt.

| Lai baltas viņām rokas
| Un tīnes no pilnības tūkst: 
| Manu pilno zelta matu
| Un ziedošo vaigu tām trūkst.

| Kur tevim otru tādu
| Kā mani, tik spriganu, rast: 
| Tām muļķēm un vārgulēm tevi
| Ne mūžam neizprast.

| Es tomēr par viņām visām
| Vēl esmu pārākā, 
| Tavs negantais prāts jau nerims
| Tai lēnīgā ikdienā;

| Un, ja es iešu tik skaista
| Tev garām kairinot,
| Tev vajdzēs tās gabalos saplēst
| Un mūžam tām ardievas dot.
 

### Mazākās kājiņas

| Zib balti zirnīši,
| Bērti pa plānu:
| Zib baltas kājiņas,
| Sīk-žigli tekot.

| Zaļoši tīrumi,
| Puķotas pļavas:
| Zib baltas kājiņas,
| Sīk-žigli tekot.

| Mazākās kājiņas
| Pa visu zemi,
| Es viņas, azotē
| Aizslēpis, sildu.

| Mazākās kājiņas
| Pa visu zemi,
| Atnesa saulīti,
| Debes' un zvaigznes;

| Debesīs putnu ceļš
| Balti zib zvaigznēm
| Balti zib kājiņas,
| Sīk-žigli tekot.
 

### Sīkie pirkstiņi

| Man liekas, šie sīkie pirkstiņi
| No rožu kristāla izdrāzti.

| Div' sarkanas saulītes aust šobrīd, 
| Kad gaisma caur pirkstiem cauri spīd.

| Tu izplēt viņus smiedamās: 
| Desmitstaraina austriņa sārtojas,

| Un spied manim acis cieti ciet:
| Visa pasaule rožainā gaismā man šķiet. ---

| Aiz tālām zemēm šie pirkstiņi mīt,
| Bet sarkana saule caur tālēm spīd.

Šie sīkie, smalkie pirkstiņi
| No rožu kristāla izdrāzti.
 

### Aiz blāvā plīvura

| Ko klīsti, prāts,
| Šo augu dien'? ---
| Tas mīļais vaigs
| Aizvien, aizvien
| Tas slaikais stāvs ---

| Kā plīvurs blāvs
| Tiem pāri klāts,
| Bet brīnummaigs
| Caur segu spīd
| Tas mīļais vaigs 
| Aizvien, aizvien
| Tas slaikais stāvs

| Tu, tāles plīvurs,
| Zili blāvs,
| Jel paveries
| Šo brīd', šo brīd' ---
| Jau staroši spīd
| Divas laimīgas acis:
| Tavs mīļais vaigs, 
| Tavs slaikais stāvs
| Man rokās slīd.

 
### Zelta tvaiks

| Man sirds ir pilna mīlas
| Kā maija zaļais ārs,
| Kā smaršas puteklīšu
| Pilns ziedošs ābeļdārzs:

| Tur diena plaukst un raso,
| Ik mirdzošs puteklīts
| Tur vijas un viļņo ap tevi,
| Klus-klusu dziesmiņu sīc.

| Tavs stāvs tiem vidū zālē
| Stāv smaidošs, smalks un slaiks 
| Tie vijas ap tevi un viļņo
| Kā kūpošs zelta tvaiks.

| Un ziedu puteklīši,
| Tie glāsta tevi un glauž,
| Ap mīļo dvēsli liegi
| Tev zīda plīvuri auž.

| Tie miljoniem plūst - bet, ja vienam,
| Tik vienam šīs acis skumst, 
| Tie klust un klīst, un saplok,
| Viss zelta mirdzums tumst.


### Šī dzīve bij tukša

| Šī dzīve bij tukša
| Tu saturu lēji;
| Šī dzīve bij kaila  ---
| Tu puķes sēji;
| Šī dzīve bij auksta ---
| Tu dvašu dvesi;
| Šī dzīve bij tumša ---
| Tu sauli nesi.

| Es atkal sauli 
| Varēšu vēstīt, 
| Mirušās krūtīs 
| Cerību dēstīt.


### Mīlas dvēsele

| Ko tirpdams stāvi
| Pie aukstām miesām?
| Tu pats viņas kāvi!

| Izbailes acīs,
| Mēms jautājums lūpās, ---
| Kas tev ko sacīs?

| Kur dvēsele dega,
| Guļ aukstās miesas
| Kā tukša sega.

| Tīmekļa sārta
| Ir mīlas dvēsele,
| Irst, tikko skārta ---

| Kā ziedu dvesma, 
| Skūpsta un aizplūst,
| Kā rīta dzesma...


### Manas ilgas

| Sen manā sirdī ilgas sēd,
| Uz āru laužas ar varu;
| Tās augu mūžu sirdi ēd, 
| Pret sienām sitas ar sparu.

| Ne acumirkli miera ļauj.
| Kā zvēri grauž krātiņa sienas, 
| Un visu, ko sirds tik mīļi skauj, 
| Tās plosa ik dienas, ik dienas...

| Mans sārtais ziediņš, mans vientulīts, 
| Kas mīļā saulē plaucis,
| Guļ, galviņu ievilcis, samīdīts: 
| Bars pāri viņam traucis.

| Mans sārtais ziediņš, starodams 
| Tu saulīti sirdī man nesi,
| Man tumšs un auksts, un negants nams, ---
| Tu līdzi tur ieslodzīts esi.

| Tur saulei nau lēkts, tur ziediem nau laiks, 
| Nau laiks, kad atelsu dzertu, 
| Tur ilgas spriežas kā katlā tvaiks, 
| Kas kalnus gaisā spertu:

| Uz priekšu, uz priekšu! tur darbs, tor spēks, 
| Vējš šaudamies svilpo gar ausīm...
| Tur prieks, tur saule, bet dusa ir grēks, 
| Uz priekšu šo zemi mēs rausim!



## Priekšpavasars

| ... Saule elpojošām acīm 
|     Nomirušā zemē raugās,
| Līdz pa mazam stingums raisās,
|     Kūst un nokrīt ledus žņaugas...


### Saules bērns

| Kad tevim uzbrukušas bēdas, ---
| Tās gremž un grauž, un iekšas plosa,
| Un sirdī mūžam atstāj pēdas.

| Bet, kad tev liels un mirdzošs prieks
| Kā saule silti noglauž galvu, ---
| Tu pasmaidi kā bērns par balvu,
| Ko aizmirst drīz: --- tas bija nieks,
| Tas bija saprotams par sevi,
| Ka prieks ik dienas silda tevi.


### Skanoša liesma

| Kā virknē domas veras 
| Un skaņas plūst un plūst:
| Tās tavas dvēsles ceras, ---
| Tā trīs un deg, un kūst;

| Tā kūst un sūrst, un kvēlo,
| Un pati sevi sveļ, ---
| To ugunis veido un tēlo,
| Iz sirds tai asinis smeļ;

| To dedzina vieglu un smalku, 
| Un brīvu no smaguma,
| Bez skaita moku un šalku
| Pār viņu izlaista:

| Lai sirdīs tā iespiesties spētu 
| Tik dziļi, cik sāpes vien rok, 
| Lai uguns sēklu sētu,
| Kur tumsā un slogā vēl smok...

| Lai sadegtos, drīzi lai dzistu,
| Tu, liesma skanošā,
| Par pelnu kopiņu kristu,
| Ko vēji iznēsā.

| Bet virknē vēl domas veras
| Un skaņas plūst un plūst:
| Tās tavas dvēsles ceras, 
| Tā trīs un deg, un kūst.

 
### Vēls saules stars

| _... Vai tad es dzenos pēc laimes,_
| _es dzenos pēc sava darba..._
| _Zaratustra_


| Uguns acīs un spītība lūpās,
| Bet nemiers valstās pa krūtīm,
| Un dziļi sirdī raud kāda balss 
| Visšaurākā, slēptākā dvēseles kaktā.
| Tev nebūs raudāt, mīļā dvēsle,
| Nau jau nekas.

| Vēls, maldū aizgājis saules stars, ---
| Viņš slīdēja garām, nelīdzi skrejot, 
| Drīz spoži mirdzot, drīz atkal dziestot, 
| Bailīgi tekājot rudens klajā,
| Kā dzenātas stirnas bēg;
| Viņš meklēja brāļus no vasaras vidus, 
| Karsto, kvēlošo saules māti ---
| Kas tevim daļas? 
| Nau jau nekas!
| Ko raudi tu, vientuļā dvēsle?

| Stars aizklīst garām, mēs paliekam ēnā, 
| Bet ēnā ir vēsāka cīņa,
| To zināja grieķi,
| Kas kaujā krita ap Leonīdu.
| Un kauja ir karsta:
| Tā stingušos locekļus sasildīs tev
| Un asaras žāvēs... 
| "Un sirdi ar," tu saki? 
| Sirds mīksta tev tiks
| Bez gala līdzcietībā un mīlā:
| Bez gala ciešanu daudz
| Tais vārgos ļaudīs! 
| Tev viņiem jālīdz, 
| Topi pilnīga, dvēsle! 
| Un neraudi vairs, 
| Bet cīnies!
| Nau jau nekas.

| Jo saules stars nāca no āras,
| Tu nespēji viļināt viņu, nespēji turēt... 
| Nau jau nekas 
| Viņš aizklīst 
| Un gaist,
| Bet dvēsle paliek, un dvēsle aug,
| Un dvēsle ir arī stars un cita saule, 
| Tā staro klusi un pastāvīgi
| Baltā vienkrāsas gaismā;
| Tā neaizklīst. 
| Klusi, dvēsle, ko raudi! 
| Nau jau nekas.

| Ne mākoņi māc šo iekšējo sauli, 
| Ne rudens to dzēš:
| Tā silti plūst ziemā un nāvē 
| Un dziļi iekšā spīd,
| Kur iespiesties nespēj 
| Sarkan-zeltainā, karstā,
| Septiņkrāsainā pasauls saule,
| Tais tumšos dziļumos zemes klēpi 
| Un vientuļās sirdīs,
| Ka tās spēcīgas top un ceļas, 
| Un kāpj uz gaismu...
| Nau jau nekas,
| Nau gluži nekas!

| Vēl tu raudi, tu, vientuļā dvēsle? 
| Jā, jā, es jūtu: tu raudi;
| Vēl asaras slepeni rit. 
| Tev nebūs raudāt!
| Jau sirds līdz malām ir asaru pilna, 
| Tik smaga top...
| Klus, beidz! es nevaru vairs! 
| Ej cīņā uzvaru gūt
| Vai krist.


### Celies!

| Tumsa, --- ne zvaigznes, 
| Kas vientuļi mirdz, 
| Krūtīs tev gaiša
| Un degoša sirds.

| Celies, kaut visi
| Tev apkārt vēl dus, 
| Nomet sald-sapņus
| Kā palagus.

| Celies un pasteidzies 
| Gurnus sev jozt,
| Visu veco dzīvi
| Sev nokrati nost!

 
### Vienīgā zvaigzne

| ... Un zini: augstākā ideja, 
| Tā nepazīsti cilvēka žēluma;

| Kas viņas ugunīs iededzies, 
| Tas neprasa, vai viņš bojā ies;

| Ne sevis, ne cita tas nevēro,
| Tas ziedo tai savu visdārgāko;

| Tas neskatās sānis, bet iet un iet, 
| Tu vari to teikt vai pelt, vai smiet;

| Tam visu visapkārt tumsa sedz,
| Tik vienu vizošu zvaigzni viņš redz. ---


### Jaunekļiem

| Jauneklim jābūt 
| Drosulim, pārgalvim: 
| Ļaudis uz ielām
| Lai skatās un brīnās!

| Kaisat pār galvām 
| Ogles ar gailēm: 
| Ļaudis ar bailēm 
| Skatās, kā cīnās.

| Noraujat apsegu, 
| Runājat dikti:
| Ļaudis, tie pikti, 
| Klausās un brīnās.

| Žibošām lāpām 
| Žilbinat acis: 
| Uztrauksies tracis, 
| Nokratīs zvīņas.

| Augšā! uz priekšu! 
| Uzvaras drosmā: 
| Ļaudis, tie trosmā 
| Sekos, kur cīnās.


### Zeltītas lapas

| Cik lēni vilkās,
| Kā svina kurpēm, 
| Šī kūtrā nakts!

| Kā dzisis gaisa
| Jau dzīves pukstiena 
| Vājais takts,

| Un galviņu lieca 
| Pie zemes krūts 
| Zaļ-zaļā zāle,

| Bez elpas gaidīja 
| Mežs un putni, 
| Un visa tāle - -
| - - - - - - - - - - -

| Ko jūs vēl skumstat, 
| Jūs jaunās dvēsles, 
| Tik zaļi sārtas?

| Pēc kūtrās nakts
| No rīta vēja
| Jūs pirmās skārtas!

| Lūk, zeltītas lapas
| Trīs kalna bērzu 
| Galotņu zaros

| Tās jūs, tās pirmās, 
| No laimes mirdzot, 
| Peld austras staros;

| Tās junda rītu,
| Bez bailēm šalcot, 
| Kaut stingušas salnā,

| Un cauru dienu
| Ar sauli runā 
| Augstajā kalnā.


### Rīta vēji

| Jūs, kas esat raudājuši, 
| Dzesinājat karstās acis: 
| Diezgan spilvens asru lacis, 
| Ceļaties, jau aust aiz mežiem!

| Modri bijāt visu nakti,
| Visas tumšā sloga drausmas, 
| Visas rupjās varas šausmas 
| Jūs visdziļāk izbaudījāt.

| Slāpētas bij domu kvēles, ---
| Tomēr sirds jums neizmisa, 
| Tomēr dzirkstis neizdzisa, 
| Paglābāt tās jaunam rītam.

| Vēsi dvašo rīta vēji,
| Augšā galvu! skaidri skatat, 
| Nost no pleciem sāpes kratat, 
| Izraujat iz krūtīm vaidus!

| Locekļiem, kas rūsējuši 
| Bezdarbībā, laužat telpas, 
| Atņematies svaigas elpas 
| Pilnas izžuvušās plaušas;

| Staipat notirpušās dzīslas, 
| Piesperat ar stingām kājām, 
| Lai jel dārd pa visām mājām, 
| Īgni norūc gulētāji!

| Atplešat tad logu slēģus: 
| Visur apkārt skaidrā tālē 
| Jauna, zaļa gaisma bālē,
| Rīta rasa mirgo zālē.

### Veca dziesma 

| To vien mēs dziedam: auksts un sājš; -
| Mums vielas trūkst, - viss vecs un vājš... 
| Mēs gribam sev jaunu dzīvi dzejot,
| Gavilēt, kaut arī bojā ejot!

### Priecīgiem ļaudīm

| Jums mūžam neizprast gaviles, 
| Kas nevaldu laužas iz dvēseles: 
| Jūs netvīkāt gurdami ēdošās sāpēs,
| Mūžam jūs neslāpsat gaviļu slāpēs.


### Vecās ligas

| _Vecais dzīves riebums atkal_
| _Paceļas iz savas migas..._

| --- Ko jūs ļāvāt ikdienībai 
| Saules smieklus slāpēt sirdī? 
| Tagad viņa, ak, jūs tirdī
| Sīkām, zemām zemes mokām.

| Mums šo ligu nau ko bīties, -
| Tās tik spēj pa zemi vīties, 
| Nespēj kalnos pakaļ dzīties,
| Ne vēl augsti celties gaisos.


### Taurētājs

| "Jā, vajga!" visi kliedz, "ka še ko darām!
| Jo posts jau tiešām manāms tiek visgarām...!"

| Pūš taurētājs taurē darboņus vākt;
| Drīz tie no malu malām sāks nākt: ---

| "Kā tad!" viens sauc, "man griba ir laba, --- 
| Nau spējas, - tas tas lielais laba... "
| Cits: "Spēja man būtu, --- bet tu ej sāc!"
| Trešs: "Es jau nu ietu, bet bailes māc..." 
| Vēl cits: "Ko bailes?! --- man nau tik vaļas!"
| Un pārējie visi: Kas mums tur daļas?

| Bet taurētājs ar savu tauri
| Laužas viens pats caur sienu cauri.

 
### Pavasara dziesma

| Pār zemi spēji dvesma iet,
| Zem dvesmas puķes un zāle zied ---
| Vai nemanāt?

| Vējš virpu virpām smiltis dzen,
| No brāzmas vecie stumbri sten ---
| Jūs nemanāt, jūs nejēdzat,
| Jūs skumji galvas karat.

| Pa klajiem laukiem aukas kauc,
| Pie debesīm melnus mākoņus jauc ---
| Jūs nemanāt, jūs nejēdzat,
| Jūs traucēkli tik barat.

| Tad lietus gāž un kokus per,
| Kā aizslāpusi zeme dzer ---
| Vēl nemanāt? vēl nejēdzat?

| Un debess dārd, un gaisi dund,
| Un niknās dusmās vētras skund ---
| Jūs nemanāt, jūs nejēdzat,
| Jūs acis cieti darāt.

| No dūsmas mostas viss pasauls ārs, 
| Drīz zaļos zeme viens vienīgs dārzs 
| Jūs nemanāt, jūs nejēdzat,
| Jūs tikai vaidēt varat.

| Jūs nemanāt, jūs nejēdzat,
| Bez jums mēs iztiksim tāpat ---
| Jūs tikai vaidēt varat.


### Lauztās priedes 

| Vējš augstākās priedes nolauza,
| Kas kāpās pie jūrmalas stāvēja -
| Pēc tālēm tās skatieniem gribēja sniegt, 
| Ne slēpties tās spēja, ne muguru liekt:

| "Tu lauzi mūs, naidīgā pretvara, --- 
| Vēl cīņa pret tevi nau nobeigta,
| Vēl ilgās pēc tāles dveš pēdējais vaids,
| Ik zarā pret varu šņāc nerimstošs naids! ..."

| Un augstās priedes pēc lauzuma
| Par kuģiem iz ūdeņiem iznira ---
| Pret vētru lepni cilājas krūts,
| Pret vētru cīņa no jauna dūc:

| "Brāz bangas, tu, naidīgā pretvara ---
| Mēs tāles sniegsim, kur laimība!
| Tu vari mūs šķelt, tu vari mūs lauzt ---
| Mēs sniegsim tāles, kur saule aust!"

 
### Uz priekšu

| Tu esi nolauzis aiz sevis tiltu,
| Kas spētu vēlreiz tevi mājās vest:
| Kur steigtos tevi skaut, līdz sirds tev siltu,
| Tev aukstās rokās siltu dvašu dvest...

| Tilts nolauzts, dzelmē nogremdētas laivas,
| Tev pretī vētrās klinšu kraujas grūst,
| Gar tukšo krastu kliedzot laižas kaivas.

| Klints asnīs rokas plēš, balsts kājām lūst...
| Uz priekšu! priekšā saules tāles plūst.

 
### Infragibilis
 
| Jūs varat izmērdēt šīs kuslās miesas,
Šo stalto stāvu liekt, šos kaulus lauzt
| Un acu starus dzēst, kas negrib snaust,
| Un samalt locekļus pēc savas tiesas;

| Jūs asām sāpēm varat garu grauzt,
| Līdz viņš ar moku pilnu muti brēktu:
| Par savu vārgu visiem vārgiem paust.- - -

| Tik veikt to nespējat: brīvs, kaut to slēgtu, 
| Un mūžīgs celsies viņš ar saules lēktu!

 
### Elēģija

#### I

| "Es ilgāk vairs to nepanesu, tēvs,
| Man dzīvām acīm jāredz tas ik dienas, 
| Un nevar līdzēt, nevar! Stāvi gļēvs
| Un mēms, un stulbs, --- viss atlec, kā no sienas...

| Ar smiekliem taisnībai tiek acīs spļauts,
| Tur vājiem vaigā sit, tur nau pat cienas
| Ne mātes svētumam - un viss tiek ļauts...

| Un miesas trīc tik, mīdītas un šaustas 
| Ak, uzlēkt, grābt, --- sirds verd, un rokas raustās..." 
| - - - - - - - - - - - - - - - - - - - - - - - -

#### II

| - - - - - - - - - - - - - - - - - - - - - -
| "Kā tevi turēt bij?! Tu aizgāji
| Brukt cīņas mutulī ar liesmu šalti . . .
| Nu, dēls, tu pārnests: - - vingrie locekļi
| Cik stīvi! cik tu kluss! cik vaigi salti!

| Kā kaisa tie, kad tavi uguns vārdi
| Mums sirdis dzēla! --- Kluss! --- Cik maigi mirdz
| Tev pierē miers, kur dega domu zārdi! ...

| Tik lūpās tev vēl kaujas niknums ņirdz:
| Tas dzeļ! ... Mēs iesim, iesim, --- rimsti, sirds!"


### Jā, riet... 

| Jā, saule riet, ak, ātri riet,
| Un augšā nakts un bailes iet.
| Jā, riet, gan riet, - un tomēr reiz aust:
| Staru pātagām tumsu šaust.


### Pavasara dienas

| Ne žēloties, ne gaust, ne gaust,
| Ar spēku šauro loku lauzt!
| Ar elkoņiem pret loku spriest, -
| I ledus brākš, kad upe briest.

| Sen saule aug, sen gaisi silst,
| Sen marta ledus pelēks dilst,-
| Jo ledus dilst, jo strauti šņāc,
| Uz straumi trauc, tos straume vāc -

| Tūkst tūkumā un krastus grauj,
| Un ledu krācot līdzi rauj,
| Pār laukiem plaši viļņus brāž,
| Iz veciem balstiem ēkas gāž;

| Kur straume dusmās pāri plūst,
| Viss mūža pamats drupās grūst,
| Ik šķērslis lūst, ik saite rīst,
| Ik drūmā cietumsiena šķīst;

| Viss krīt, kas šķir, kas spiež un draud, -
| Cik tāļi acis redzēt jaud:
| Viens vienīgs līdzens ūdens lauks,
| Kā milzīgs pildīts dzīves trauks.

 
### Fiat justitia!

| Tik viena vienīga ir taisnība,
| Tā pati mūžīga un negrozāma -
| No sākta gala viņa bijusi:
| Tā uztur kārtībā šo pasauli, 
| Un visa pasaule kad bojā ietu, 
| Tad tomēr taisnība vēl paliktu. 
| Fiat justitia, ruat mundus!

#### * * *

| Tā augstā krēslā sēd pār pasauli, 
| Ar mākoņiem sedz savu majestāti 
| Un skaidro skatu - sedz ar aizsaini.
| Uz dzelzs un akmens balstās viņas krēslis, 
| Uz līķu kaudzēm, kaulu piramīdēm,
| No lielgabaliem lieti uzvarstabi 
| Ir krēsla kājas; sēdeklis ir pīts
| No važām, kurās tautas bija kaltas, 
| Kas noziegušās: mazas būdamas. 
| Tai rokās svara kausi: vienā kausā 
| Ir taisnas asinis, bet otrā zobens,
| Un otrais kauss aizvien uz zemi sver. 
| Tā tērpta sarkani ar zelta audiem,
| Smags zīda mētels tai pār pleciem čaukst; 
| Ap vidu kalta plata vara josta,
| No svina kurpes dzelžu papēžiem;
| Pie sāniem likums, pātaga un cirvis. 
| Tā, plānās lūpas sakodusi, sēd,
| Un katrs vārds, kas izspiežas tām cauri, 
| Ir griezīgs asmenis un dunča gals.
| Tā runā pavēlēs un spriedumos, 
| Kas gaisā švīkst kā cirvja cirtieni. 
| Viss, ko tā teic, tiek tūdaļ izpildīts, 
| Līdz zeme pārplūzdama sārtojas 
| Un asins atspīd debesīs kā blāzma. 
| Fiat justitia, ruat mundus!

#### * * *

| Un paceļas no krēsla taisnība,
| Iet izplatīt pa zemēm savu varu -
| Tā izlīdzinājošā taisnība;
| Tā, acis aizsegusi, akla staigā,
| Tā neuzlūko, vai kāds labs vai ļauns, 
| Tā soda darbu, neredz cēloņus,
| Ne vaigu bālumu, ne asaras,
| Ne kalsnās rokas, kuras izmisumā
| Bij ilgi lauzītas, pirms noziedzās. 
| Jā, - garos mūžos taisnība gan būs
| Vai veca tikusi, un acis tumšas
| No mūžam nenoņemtā aizsaiņa. 
| Man arī šķiet: tā drusku pakurla 
| Vai ausis aizbāzusi mīkstu vilnu,
| Jo aukstu seju viņa garām iet,
| Kur aizsmakušas balsis kliedz pēc viņas: 
| Lai, lai sev kliedz, tas viņu negrozīs,
| Uz kliedzējiem nekad tā neklausījās -
| Fiat justitia, ruat mundus!

#### * * *

| --- Stāvs arī nau tik stalts, kā šķiet no tāles,
| Tā laiskiem soļiem. ļodzīdamās iet,
| Ka retu reiz var panākt vainīgo,
| Un cietie kaulu pirksti taisno grābj. 
| Tik osmas spēja tai vēl smalka liekas: 
| Jau iztālīm jūt būdās dūmu smaku 
| Un labprāt apiet tām ar loku apkārt. 
| Bet, ja tur tomēr reizēm nākas būt, 
| Tā pazemīga līdzi pazemīgiem
| Un pieklājīga; rāma, bailīga; 
| Nekad tā nelien bezkaunīgi acīs;
| Un lepna ar tā nau, kā šķiet no tāles. 
| Kad nauda runā, viņa klusu cieš! 
| Ļauj kaulēties ar sevi, pajokoties, 
| Prot piemēroties visām vajadzībām. 
| Ar vareniem un drošiem tā ir droša; 
| Tur viņa rādās visā stingrībā,
| Sev neļauj blakus sēdēt žēlastībai, 
| Tad viņas spriedumam nau pretrunas: 
| Lai visa pasaule vai bojā iet,
| Lai tūkstots balsīm vaidu vaidi kāpj, 
| Lai draud un zobus griež, un dūres ceļ, 
| Tad tomēr taisnībai ir jānotiek ---
| Tā nikni samin visus pretekļus
| Un visas nezāles ar saknēm izrauj- 
| Tai pieder pēdējs vārds un pēdējs --- lāsts --- 
| Fiat justitia, ruat mundus!

#### * * *

| Jā, vecā taisnība, tas acīm redzams, 
| Aizvien top vecāka un vājāka,
| Un viņas dienas ir jau skaitītas.
| Ik stundas zūd tai spēki, tikai niknums 
| Vēl augtin aug un pikta ļaunprātība, 
| Ap lūpām zemi nenovīdīgs vaibsts, 
| Un mute sašķiebta no ņirguma.
| Tai kājas ļogās, izkaltušos kaulos 
| Dilst dzīvās smaganas, un kruķis vien 
| Vēl balsta saļimstošo ģindeni.
| Bet kruķis sper vēl pakritušo miesu 
| Un kāja lūdzējam pa vaigu min.
| Fiat justitia, ruat mundus!

 
#### *  *  *

| Ir laiks jau nācis vecai taisnībai,
| Tās dzīve zobu galā karājas.
| Drīz sabruks milzu stāvs, ka norībēs
| No kauliem klabošiem un tukšās paures, 
| Un gaisā celsies melni putekļi
| No izžuvušā asins plūduma,
| Kas viņas vārdā tika izlaistīts
| No viņas ģiftīgajām siekalām,
| No gruvekļiem un vecās ēkas trūdiem, 
| No tūkstošgadu mēslu salašnām,
| Kas krājās nomestas un pūdamas
| Un visu gaisu zemē smacināja,
| Ka elpa aizrāvās no ļauniem tvaikiem 
| Un zaļai dzīvībai bij jānosmok.
| Bet trūdiem cauri zaļi asni dīgst,
| Un jauna pasaule virs vecās ceļas-
| Ruat justitia, fiat mundus!


### Pastara diena

| _Dies irae, dies illa_
| _Solvet urbem in favilla._

| Daudz karstas sirdis
| Pukstēt rims,
| Daudz zaļi stāvi 
| Vēl lauzti ļims;

| Daudz nakšu tumsa 
| Vēl ļaudis segs, 
| Daudz dzirkstis dzisīs, 
| Pirms liesma degs;

| Un balti kauli
| Vēl laukus klās, 
| Daudz asins plūdīs, 
| Pirms vaidi stās;

| Daudz krūtis stenēs,
| Daudz pleci līks
| Un celsies atkal,
| Un atkal slīks;

| Daudz viļņi velsies
| Un atkritīs,
| Bet atkal un atkal 
| Tos vētra dzīs; -

| Simt-simti pamirs - 
| Vēl tas nau gals:
| Simt-tūkstošus jaunus
| Sauc vietā balss.

| Jo viena apklust, 
| Jo desmit brēc, 
| Līdz tuvu, tāļu 
| Viss plašums rēc,

| Līdz zemā zeme 
| No dusmām trīc,
| Ik smilšu graudiņš, 
| Ko minat, dīc;

| No zemes trīces
| Jums nami grūst,
| Dzelzs cietākie stabi 
| Jums pāri lūst;

| Tās akmens kaudzes, 
| Ko cēlāt jūs tvert, 
| Tās kritīs uz jums 
| Jūsu asinis dzert.

| Klints jūsu pilis
| No pleciem sev vels 
| Un, brīvi sliedamās, 
| Galvu cels.

| Kur tad jūs bēgsat, 
| Kurš kalns jūs glābs? 
| Kad kalns un leja 
| Tik atriebt slāps!

| Kurš ezers, jūra 
| Jums tversmi dos? 
| Tie šļāks pār zemi, 
| Jūs aizskalos;

| Gan melnos dumbros 
| Jūs skriesat līst?
| Pret jums tie balti, 
| Jūs neatzīst;

| Bet mēmā zeme 
| Tad muti vērs 
| Un aprīs jūs,
| Un kūpēs sērs.


## Epilogs

| _... Laukā brīvi vēji šaudās..._
| _Debess, pēkšņi atvērdamās,_
| _Paceļas līdz bezgalībai..._
| _No "Ave sol!"_

 
### Gara gaita

| - - - - - - - - - - - - - - - - - - - - - - -
| --- Bet vis vēl augstāk, augstāk gaita sniedz:
| Viss tālē raucas it kā rīta ēna,
| Jau gaisa kārta top tik dzestri rēna,
| Bet vis vēl augstāk tava gaita sniedz... 
| - - - - - - - - - - - - - - - - - - - - - - - - - -
| No miesām visas risa zemes saites,
| Viss naids un dusmība, viss ļaunums, kaites;
| Bez žēluma, bez pagātnes, bez vainas 
| Tu skati priekšā zelta rīta ainas;
| Gars brīvus spārnus dzidrē cilā liegi;
| Tik balta dvēsle mirdz kā kalnu sniegi;
| Gaist viss, kas rupjis, smags, --- spīd smalkais maigums
| Kā zvaigžņu būtes caurspīdīgais zaigums...
| ... Bet vis vēl augstāk tava gaita sniedz... 
| - - - - - - - - - - - - - - - - - - - - - - - - - -
| Aiz tevis raucas viss kā rīta ēna,
| Jau gaisa kārta top tik dzestri rēna,
| Bet augstāk saulei pretī gaita sniedz,
| Un mūžos gala nau, kas gaitu liedz...
| - - - - - - - - - - - - - - - - - - - - - - - - - -



一二三四五

